### ISSUE TITLE
wheel-gestures not working?

### ISSUE THREAD

**Issue by siamahnaf198** [xiel/embla-carousel-wheel-gestures#152]
Hello, I am trying to use Embla carousel with `drag free`, `wheel-gesture`s and also with `progress`. But I am facing one problem When I am trying to integrate `embla-carousel-wheel-gestures`. It is not working. Here I am trying to scroll in `x-axis(horizontal)` with mouse wheel. Can you help me?

CodeSandBox- https://codesandbox.io/s/fast-fast-527jo

**Comment by davidcetinkaya** [comment]
@siamahnaf198,

I haven't tried your CodeSandbox with a mouse wheel but it's working as expected with a trackpad. I'm just guessing here because I think @xiel can answer this question better than me, but maybe your mouse wheel is triggering vertical scroll instead of horizontal?

If that's the case, have you tried setting the [forceWheelAxis](https://www.embla-carousel.com/plugins/wheel-gestures/#forcewheelaxis) option to `y` like so:

```js
 const [viewportRef, embla] = useEmblaCarousel(
    {
      dragFree: true,
      containScroll: "trimSnaps"
    },
    [WheelGesturesPlugin({ forceWheelAxis: 'y' })]
  );
```

Best,
David

**Comment by siamahnaf198** [comment]
Working but not smooth, I think.

**Comment by davidcetinkaya** [comment]
@siamahnaf198 you're welcome to share a screen recording that demonstrates the problem in that case.

**Comment by xiel** [comment]
@siamahnaf198  This means your mouse does not emit pixel precision scroll events. Sorry, but this works as intended for now. You will only get the best UX when your hardware emits them in pixel precision instead of lines, like eg. Microsoft Precision Touchpads (Surface), all Apple Touchpads and Mouse etc.
