### ISSUE TITLE
Remove Peer Dep

### ISSUE THREAD

**Issue by Eben-Hafkamp** [xiel/embla-carousel-wheel-gestures#174]
### Describe the bug

After installing the embla-carousel-wheel-gestures plugin and using it successfully with embla-carousel-vue I keep getting npm warnings because embla-carousel is a peer dependency of the embla-carousel-wheel-gestures package. 

### Steps to reproduce

1. Install embla-carousel-vue
2. Install embla-carousel-wheel-gestures
3. See the warnings in the terminal

### Expected behavior

- As the plugin functions properly I would like to see a clear terminal void of issues instead of bloating my project with unnecessary packages.

**Comment by xiel** [comment]
@Eben-Hafkamp Mh... interesting. Do you use npm, yarn, pnpm? Isn't `embla-carousel-vue` installing the base package `embla-carousel` as it's dependencies? 

Sadly the peer dependencies are a bit messed up in my experience (in general).

**Comment by Eben-Hafkamp** [comment]
Hey @xiel I am using **pnpm** and I can confirm that `embla-carousel-vue` is listing `embla-carousel` as an internal `dependency`. I'd prefer to keep it there, instead of downloading the library myself in order to avoid confusion within the project.

I've also had mixed experiences with peer deps in the past but I can see its usefulness. As it stands though, there are around 5 flavours of the library so I'm assuming anyone not using the base JS version will also be getting these warnings. 

Do you think another package manager will recognise the embedded library? From my understanding **pnpm** does a good job of bundling mutual libraries.

**Comment by xiel** [comment]
I will need to test that again. The problem is the base package is a dependency of this plugin. So it should either be declared as a peer dep or a normal dep.

Behavior I've seen with yarn before was, that for example a project had a base package installed, and later installed a plugin with the base package as a real dependency. Then the later install would install the base package again with a newer version, without deduplicating. And one ends up with two installed versions of the same package.

**Comment by davidjerleke** [comment]
@Eben-Hafkamp have you tried installing any of the other [plugins](https://www.embla-carousel.com/plugins/#choose-a-plugin)? Does that trigger any warnings?
