### ISSUE TITLE
How to import without using npm?

### ISSUE THREAD

**Issue by tbqmax** [xiel/embla-carousel-wheel-gestures#206]
I appreciate your understanding and patience as I'm still learning. I'm having trouble figuring out how to `import` this specific plugin without using **npm**, and I could really use some guidance.

For all other embla plugins, I've been able to download the code directly and import it successfully. 

For example, with `embla-carousel-fade` I download the code from [JSDELIVER](https://cdn.jsdelivr.net/npm/embla-carousel-fade@8.1.8/+esm) into my local `embla-fade.js` file. Then, in another file, I import it like this:

```js
import EmblaCarousel from "embla.js";
import ClassNames from "embla-fade.js";

customElements.define('my-embla', class MyEmbla extends HTMLElement { ... });
```

This approach works perfectly for me and I'm comfortable doing this way. However, I'm struggling to replicate this process with "embla-carousel-wheel-gestures" plugin. Could someone please provide some guidance or advice on how to achieve this?

Thank you so much for your help!

**Comment by xiel** [comment]
Hey @tbqmax 

when u download & save the [esm file](https://cdn.jsdelivr.net/npm/embla-carousel-wheel-gestures/+esm) from here, you should be able to import the plugin like that:

`import { WheelGesturesPlugin } from 'embla-carousel-wheel-gestures.js'`

The reason for that is that we are currently using a named export, instead of a default export.
`export{t as WheelGesturesPlugin}`

Hope that helps ✌️
